### ISSUE TITLE
update async.vim and vim-lsp

### ISSUE THREAD

**Issue by prabirshrestha** [tjdevries/nvim-langserver-shim#15]
I fixed a couple of bug related in async.vim and vim-lsp. I was about to update it but noticed that you have slightly diverged the changes. I also did add some of your changes like `abort` in functions. Do you still want to maintain a copy or directly reference these plugins instead.

Also any reason why you need a `lock` in lsp?

**Comment by tjdevries** [comment]
So currently I'm not sure exactly where I'm planning on taking this part of the project.

On one hand, I'm currently waiting on a few things on the neovim side about the lua interface. Once that happens, I think I will rewrite parts of the LSP to use Lua instead of VimL.

However, I'm open to trying to make it available for both Vim and Neovim. I'm just not sure vimscript will be able to keep up once we start getting into things like sending updates of the file to the server in real time, and managing various items like that.

Also I added the lock cause I thought I was going to need it, and now I'm not so sure. :)

**Comment by prabirshrestha** [comment]
Totally makes sense. thanks for clearing out.

As mentioned here https://github.com/neovim/neovim/issues/5522#issuecomment-275962672 I would be supporting `vim-lsp` to with multiple core providers so neovim can take full advantage of remote plugins. If neovim autocompiles vim script to luascript and run might be I don't need to even worry about this :)
